### ISSUE TITLE
RuntimeHierarchy AddToPsueDoScene Not working 

### ISSUE THREAD

**Issue by deltamish** [yasirkula/UnityRuntimeInspector#1] opened 2018-03-13 05:58 UTC
I followed the steps as you said. Dragged RuntimeHierarchy Prefab into my scene, Created A new Script with following code 

` using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RuntimeInspectorNamespace;
public class RunTimeHirearchyHelper : MonoBehaviour {

  public RuntimeHierarchy runtimeHierarchy;
  public Transform TestTransform;
	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		runtimeHierarchy.AddToPseudoScene("Test scene",TestTransform);
	}
}

The Test Psudescene is being created but the objects /children are empty and doesnt show anything

**Comment by yasirkula** [comment] 2018-03-13 08:35
It actually works for me using the same code, that's weird. I've tested it on Unity 5.6.2f1. Which Unity version are you using?

![ss](https://user-images.githubusercontent.com/10211608/37330453-2dfde45a-26b2-11e8-8eab-b88c34ff05d0.png)

P.S. As a side note, it is sufficient to call AddToPseudoScene just once (maybe in the Start function).

**Comment by deltamish** [comment] 2018-03-16 12:18
Hey,

I am using Unity Version 2018.1b 

Haha yeah. since it was not coming I added it to Update. Hoping it would come 

thanks

**Comment by yasirkula** [comment] 2018-03-16 21:31
I was able to reproduce the issue on Unity 2017.3.0p2. It was caused by a bug in Unity UI. It can be resolved by changing Pos X of the HierarchyItemRoot-Content-ExpandToggle prefab. When Pos X is 0, you can't click the dropdown, when it is 0.001, you can. Strange, huh?

I'll update the package shortly.

**Comment by yasirkula** [comment] 2018-03-16 21:42
Aaaand it's live! ^^

**Closed** 2018-03-26 18:29 UTC
